name: "Extract, transform and load"

on:
  workflow_dispatch:
  #schedule:
  #  - cron: "*/15 * * * *"

permissions: write-all

concurrency:
  group: "etl"
  cancel-in-progress: true

jobs:
  los_angeles_county:
    name: Los Angeles County Registrar-Recorder/County Clerk
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - id: checkout
        name: Checkout
        uses: actions/checkout@v3

      - id: install
        name: Install Python dependencies
        uses: ./.github/actions/install

      - id: download
        name: Download
        run: pipenv run python -m src.los_angeles_county.download --election 2026-june-primary
        shell: bash

      - id: transform
        name: Transform
        run: pipenv run python -m src.los_angeles_county.transform --election 2026-june-primary
        shell: bash

      - id: commit
        name: Commit
        uses: ./.github/actions/commit
        with:
          message: "Fetched latest from the Los Angeles County Registrar-Recorder/County Clerk"

  ca_secretary_of_state:
    name: California Secretary of State
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - id: checkout
        name: Checkout
        uses: actions/checkout@v3

      - id: install
        name: Install Python dependencies
        uses: ./.github/actions/install

      - id: download
        name: Download
        run: pipenv run python -m src.ca_secretary_of_state.download --election 2026-june-primary
        shell: bash

      - id: transform
        name: Transform
        run: pipenv run python -m src.ca_secretary_of_state.transform --election 2026-june-primary
        shell: bash

      - id: commit
        name: Commit
        uses: ./.github/actions/commit
        with:
          message: "Fetched latest from the California Secretary of State"

  orange_county:
    name: Orange County Registrar of Voters
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - id: checkout
        name: Checkout
        uses: actions/checkout@v3

      - id: install
        name: Install Python dependencies
        uses: ./.github/actions/install

      - id: download
        name: Download
        run: pipenv run python -m src.orange_county.download --election 2026-june-primary
        shell: bash

      - id: transform
        name: Transform
        run: pipenv run python -m src.orange_county.transform --election 2026-june-primary
        shell: bash

      - id: commit
        name: Commit
        uses: ./.github/actions/commit
        with:
          message: "Fetched latest from the Orange County Registrar of Voters"

  export:
    name: Export CSV
    runs-on: ubuntu-latest
    timeout-minutes: 5
    needs: [los_angeles_county, ca_secretary_of_state, orange_county]
    steps:
      - id: checkout
        name: Checkout
        uses: actions/checkout@v3

      - id: install
        name: Install Python dependencies
        uses: ./.github/actions/install

      - id: export
        name: Export to CSV
        run: pipenv run python -m src.export
        shell: bash

      - id: commit
        name: Commit
        uses: ./.github/actions/commit
        with:
          message: "Exported CSV"

  kpcc:
    name: Deploy for KPCC
    runs-on: ubuntu-latest
    timeout-minutes: 5
    needs: [los_angeles_county, ca_secretary_of_state, orange_county]
    steps:
      - id: checkout
        name: Checkout
        uses: actions/checkout@v3

      - id: install
        name: Install Python dependencies
        uses: ./.github/actions/install

      - id: optimize-kpcc
        name: Optimize for KPCC
        run: pipenv run python -m src.optimize kpcc
        shell: bash

      - id: commit
        name: Commit
        uses: ./.github/actions/commit
        with:
          message: "Optimized JSON"

  pages:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    timeout-minutes: 5
    needs: [export, kpcc]
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: checkout
        name: Checkout
        uses: actions/checkout@v3

      - name: Setup Pages
        uses: actions/configure-pages@v2

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: './data'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
