name: "Extract, transform and load"

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */12 * * *"

permissions:
  contents: write
  pages: write
  deployments: write
  id-token: write

concurrency:
  group: "etl"
  cancel-in-progress: true

jobs:
  los_angeles_county:
    name: Los Angeles County Registrar-Recorder/County Clerk
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        name: Checkout
        uses: actions/checkout@v3

      - id: install
        name: Install Python dependencies
        uses: ./.github/actions/install

      - id: download
        name: Download
        run: pipenv run python -m src.los_angeles_county.download
        shell: bash

      - id: transform
        name: Transform
        run: pipenv run python -m src.los_angeles_county.transform
        shell: bash

      - id: commit
        name: Commit
        uses: ./.github/actions/commit
        with:
          message: "Fetched latest from the Los Angeles County Registrar-Recorder/County Clerk"

  ca_secretary_of_state:
    name: California Secretary of State
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        name: Checkout
        uses: actions/checkout@v3

      - id: install
        name: Install Python dependencies
        uses: ./.github/actions/install

      - id: download
        name: Download
        run: pipenv run python -m src.ca_secretary_of_state.download
        shell: bash

      - id: transform
        name: Transform
        run: pipenv run python -m src.ca_secretary_of_state.transform
        shell: bash

      - id: commit
        name: Commit
        uses: ./.github/actions/commit
        with:
          message: "Fetched latest from the California Secretary of State"

  ny_state_board_of_elections:
    name: New York State Board of Elections
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        name: Checkout
        uses: actions/checkout@v3

      - id: install
        name: Install Python dependencies
        uses: ./.github/actions/install

      - id: download
        name: Download
        run: pipenv run python -m src.ny_state_board_of_elections.download
        shell: bash

      - id: transform
        name: Transform
        run: pipenv run python -m src.ny_state_board_of_elections.transform
        shell: bash

      - id: commit
        name: Commit
        uses: ./.github/actions/commit
        with:
          message: "Fetched latest from the New York State Board of Elections"

  export:
    name: Export CSV
    runs-on: ubuntu-latest
    needs: [los_angeles_county, ca_secretary_of_state, ny_state_board_of_elections]
    steps:
      - id: checkout
        name: Checkout
        uses: actions/checkout@v3

      - id: install
        name: Install Python dependencies
        uses: ./.github/actions/install

      - id: export
        name: Export to S3
        run: pipenv run python -m src.export
        shell: bash

      - id: commit
        name: Commit
        uses: ./.github/actions/commit
        with:
          message: "Exported CSV"

  kpcc:
    name: Deploy for KPCC
    runs-on: ubuntu-latest
    needs: [los_angeles_county, ca_secretary_of_state]
    steps:
      - id: checkout
        name: Checkout
        uses: actions/checkout@v3

      - id: install
        name: Install Python dependencies
        uses: ./.github/actions/install

      - id: optimize-kpcc
        name: Optimize for KPCC
        run: pipenv run python -m src.optimize kpcc
        shell: bash

      - id: commit
        name: Commit
        uses: ./.github/actions/commit
        with:
          message: "Optimized JSON"

      - id: upload
        name: Upload to S3
        run: pipenv run python -m src.upload
        shell: bash
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
          AWS_BUCKET: ${{ secrets.AWS_BUCKET }}
          AWS_PATH_PREFIX: ${{ secrets.AWS_PATH_PREFIX }}

  pages:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    needs: [export]
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: checkout
        name: Checkout
        uses: actions/checkout@v3

      - id: install
        name: Install Python dependencies
        uses: ./.github/actions/install

      - name: Setup Pages
        uses: actions/configure-pages@v2

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: './data'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
