name: "Extract, transform and load"

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */12 * * *"

jobs:
  etl:
    name: ETL
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        name: Checkout
        uses: actions/checkout@v3

      - id: setup-python
        name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pipenv'

      - id: install-pipenv
        name: Install pipenv
        run: curl https://raw.githubusercontent.com/pypa/pipenv/master/get-pipenv.py | python
        shell: bash

      - id: install-python-dependencies
        name: Install Python dependencies
        run: pipenv install --dev --python=`which python`
        shell: bash

      - id: download-la
        name: Download raw LA County data
        run: pipenv run python -m src.los_angeles_county.download
        shell: bash

      - id: transform-la
        name: Transform LA County data
        run: pipenv run python -m src.los_angeles_county.transform
        shell: bash

      - id: download-sos
        name: Download Secretary of State data
        run: pipenv run python -m src.ca_secretary_of_state.download
        shell: bash

      - id: transform-sos
        name: Transform Secretary of State data
        run: pipenv run python -m src.ca_secretary_of_state.transform
        shell: bash

      - id: export
        name: Export to S3
        run: pipenv run python -m src.export
        shell: bash

      - id: upload
        name: Upload to S3
        run: pipenv run python -m src.upload
        shell: bash
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
          AWS_BUCKET: ${{ secrets.AWS_BUCKET }}
          AWS_PATH_PREFIX: ${{ secrets.AWS_PATH_PREFIX }}

      - id: commit
        name: Commit
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git config pull.rebase false
          git pull origin $GITHUB_REF
          git add ./data
          git commit -m "Added latest ETL" --author="palewire <palewire@users.noreply.github.com>" && git push || true
        shell: bash
